version: "3.4"
services:
    piranha:
        build: .
        container_name: piranha_web
        environment:
            - CORECLR_PROFILER_PATH_64=./runtimes/linux-x64/native/ContrastProfiler.so
            - CORECLR_ENABLE_PROFILING=1
            - CORECLR_PROFILER={8B2CE134-0948-48CA-A4B2-80DDAD9F5791}
            - CONTRAST_CONFIG_PATH=./contrast_security.yaml
        ports:
            - "5000:5000"